pysite/aperitivos/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from pysite.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('<slug:slug>', video, name='video'),
    path('', indice, name='indice'),

]

pysite/base/urls.py
from django.urls import path
from pysite.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pysite/modulos/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from pysite.aperitivos.views import video, indice
from pysite.modulos import views

app_name = 'modulos'
urlpatterns = [
    path('<slug:slug>', views.detalhe, name='detalhe'),

]

pysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import include, path
from pysite.base.views import home

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pysite.base.urls')),
    path('aperitivos/', include('pysite.aperitivos.urls')),
    path('modulos/', include('pysite.modulos.urls')),
]

if settings.DEBUG:
    import debug_toolbar
    urlpatterns.append(
        path('__debug__/', include(debug_toolbar.urls))
    )

pysite/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Video: {self.titulo}'

pysite/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.core.mail import send_mail
from django.db import models
from django.utils import timezone
from django.utils.translation import gettext_lazy as _


class UserManager(BaseUserManager):
    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_('first name'), max_length=30, blank=True)
    email = models.EmailField(_('email address'), unique=True)
    is_staff = models.BooleanField(
        _('staff status'),
        default=False,
        help_text=_('Designates whether the user can log into this admin site.'),
    )
    is_active = models.BooleanField(
        _('active'),
        default=True,
        help_text=_(
            'Designates whether this user should be treated as active. '
            'Unselect this instead of deleting accounts.'
        ),
    )
    date_joined = models.DateTimeField(_('date joined'), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = 'email'
    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _('user')
        verbose_name_plural = _('users')

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name plus the last_name, with a space in between.
        """
        full_name = '%s' % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pysite/modulos/models.py
from django.db import models
from ordered_model.models import OrderedModel
from django.urls import reverse

# Create your models here.
class Modulo(OrderedModel):
    titulo = models.CharField(max_length=64)
    publico = models.TextField()
    descrico = models.TextField()
    slug = models.SlugField(unique=True)

    class Meta(OrderedModel.Meta):
        pass

    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug':self.slug})

pysite/aperitivos/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render

from pysite.aperitivos.models import Video


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})

def video(request, slug):
    video = Video.objects.get(slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

pysite/base/views.py
from django.http import HttpResponse
from django.shortcuts import render
from pysite.modulos import facade
# Ver o {}


def home(request):
    return render(request, 'base/home.html', {})

pysite/modulos/views.py
from django.shortcuts import render

# Create your views here.
def detalhe(request, slug):
    pass

pysite/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Site do Rafa - Aperitivo{% endblock title %}
{% block description %} Página com todos os vídeos gratuitos{% endblock description %}
{% block body %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
		  <!-- Google Tag Manager -->
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-MBBM3SG');</script>
	<!-- End Google Tag Manager -->

	  <!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177540018-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-177540018-1');
	</script>
	  <div class="container">
		  	<div class="row">
		<div class="col-md-12">
			<h1>Lista de Vídeos Aperitivos</h1>
			<ol>
				{% for video in videos %}
				<li><a href="{{video.get_absolute_url}}">{{ video.titulo | default:"Faltando Título"}}</a></li>
				{% empty %}
					<li> Não foi encontrado nenhum vídeo de aperitivo</li>
				{% endfor %}
			</ol>
		</div>
    </div>
    </div>
	  {% endblock body %}

pysite/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Site do Rafa - Aperitivo{% endblock title %}
{% block description %} Página com vídeo de teste{% endblock description %}
{% block body %}

<!DOCTYPE html>
<html lang="pt-br">
  <head>
		  <!-- Google Tag Manager -->
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-MBBM3SG');</script>
	<!-- End Google Tag Manager -->

	  <!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177540018-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-177540018-1');
	</script>
	  <div class="container">
	<div class="row">
		<div class="col-md-12">
            '<h1>{{ video.titulo |default:"Faltando Título" }}</h1>'
			<iframe src="https://player.vimeo.com/video/{{ video.vimeo_id}}" width="640" height="480" frameborder="0" allow="autoplay; fullscreen" allowfullscreen></iframe>
        </div>
    </div>

	  {% endblock body %}

pysite/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
  <head>
		  <!-- Google Tag Manager -->
	<script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
	new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
	j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
	'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
	})(window,document,'script','dataLayer','GTM-MBBM3SG');</script>
	<!-- End Google Tag Manager -->

	  <!-- Global site tag (gtag.js) - Google Analytics -->
	<script async src="https://www.googletagmanager.com/gtag/js?id=UA-177540018-1"></script>
	<script>
	  window.dataLayer = window.dataLayer || [];
	  function gtag(){dataLayer.push(arguments);}
	  gtag('js', new Date());

	  gtag('config', 'UA-177540018-1');
	</script>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title> {% block title %}Site do Rafa{% endblock title %}</title>

    <meta name="description" content="{% block description %} Página do Site do Rafa {% endblock description %}">
    <meta name="author" content="Rafael Gomes">
	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="{% static 'js/jquery.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
  </head>
  <body>
	  <!-- Google Tag Manager (noscript) -->
	<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-MBBM3SG"
	height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
	<!-- End Google Tag Manager (noscript) -->

  <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <a class="navbar-brand" href="{% url 'base:home' %}">Site do Rafa</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Módulos
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% for modulo in MODULOS %}
           <a class="dropdown-item" href="{{modulo.get_absolute_url}}">{{modulo.titulo}}</a>
          <div class="dropdown-divider"></div>
            {% endfor %}
        </div>
      </li>
    </ul>

  </div>
</nav>

      {% block body %}{% endblock body %}




  {% include 'base/footer.html' with contato_email='rafael1717yy@gmail.com' only %}

  </body>
</html>

pysite/base/templates/base/footer.html
 <footer class="main-footer mt-5 pt-4">
	  <div class="container">
		  <div class="row">
			  <div class="col">
				  <h5>Entre em Contato</h5>
				  <address>
					  <br/>
					  <a href="mailto:{{contato_email}}">rafael1717yy@gmail.com</a>
				  </address>

			  </div>
		  </div>
	  </div>
	  <div class="rights pb-4 text-light"></div>
	  <div class="container">
		  <div class="row">
			  <div class="col">
				  {% now 'Y' %} Site do Rafa. Todos os direitos reservados.
			  </div>
		  	</div>
	  </div>


  </footer>

pysite/base/templates/base/home.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br"
<head>

<meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Site do Rafa</title>

    <meta name="description" content="Página do Site do Rafa">
    <meta name="author" content="Rafael Gomes">

	<link rel="icon" type="image/png" href="{% static 'img/favicon.png' %}" />
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
	<script src="{% static 'js/jquery.min.js' %}" ></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
  </head>

<body>
<div class="container">
	<div class="row">
		<div class="col-md-12">

				<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
					<span class="navbar-toggler-icon"></span>
				</button> <a class="navbar-brand" href={% url 'base:home' %}>Site do Rafa</a>
				<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
					<ul class="navbar-nav">
						<li class="nav-item active">
							 <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item">
							 <a class="nav-link" href="#">Link</a>
						</li>
						<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="http://example.com"
								id="navbarDropdownMenuLink2">Dropdown link</a>
							<div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink2">
								 <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider">
								</div> <a class="dropdown-item" href="#">Separated link</a>
							</div>
						</li>
					</ul>
					<form class="form-inline">
						<input class="form-control mr-sm-2" type="text">
						<button class="btn btn-primary my-2 my-sm-0" type="submit">
							Search
						</button>
					</form>
					<ul class="navbar-nav ml-md-auto">
						<li class="nav-item active">
							 <a class="nav-link" href="#">Link <span class="sr-only">(current)</span></a>
						</li>
						<li class="nav-item dropdown">
							 <a class="nav-link dropdown-toggle" href="http://example.com" id="navbarDropdownMenuLink" data-toggle="dropdown">Dropdown link</a>
							<div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdownMenuLink">
								 <a class="dropdown-item" href="#">Action</a> <a class="dropdown-item" href="#">Another action</a> <a class="dropdown-item" href="#">Something else here</a>
								<div class="dropdown-divider">
								</div> <a class="dropdown-item" href="#">Separated link</a>
							</div>
						</li>
					</ul>
				</div>

			<div class="jumbotron">
				<h2>
					Site do Rafa
				</h2>
				<h4 class="mt-4">Entre na fila de espera</h4>
				<form action="https://sitedorafa.us2.list-manage.com/subscribe/post?u=3227bd8d5d167ffd43baeb2d0&amp;id=1770c94df9" method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form" class="form-row align-items-center" target="_blank" novalidate>

  <div class="form-row align-items-center">
    <div class="col-auto">
      <label class="sr-only" for="mce-EMAIL">Email</label>
      <input type="email" value="" name="EMAIL" class="form-control required" id="mce-EMAIL" placeholder="exemplo@email.com">
    </div>

	  <!-- real people should not fill this in and expect good things - do not remove this or risk form bot signups-->
    <div style="position: absolute; left: -5000px;" aria-hidden="true"><input type="text" name="b_3227bd8d5d167ffd43baeb2d0_1770c94df9" tabindex="-1" value=""></div>
	<div class="col-auto">
      <label class="sr-only" for="mce-EMAIL">Email</label>
      <input type="text" value="" name="FNAME" class="form-control" id="mce-FNAME" placeholder="Seu Nome">
      	</div>
    <div class="col-auto">
      <input type="submit" value="Salvar" name="subscribe" id="mc-embedded-subscribe" class="btn btn-primary"></div>


	</div>
  </div>
</form>
				<p>
					Confira em breve mais informações sobre o site que será lançado.
				</p>
				<form>

</form>
			</div>
			<div class="row">
				<div class="col-md-12">
					<div class="card">
						<h5 class="card-header">
							Mais detalhes...
						</h5>
						<div class="card-body">
							<p class="card-text">
								<img src="{% static 'img/loading3.png' %}" />
							</p>
						</div>
					</div>
				</div>
			</div>
			<div class="row">
				<div class="col-md-12">
				</div>
			</div>
		</div>
</div>